import Head from 'next/head'
import Image from 'next/image'
import { getData } from '@/utils/data'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ info }) {
  console.log(info)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          info.map((item, id) => {
            return (
              <div key={id}>
                <Image 
                  src={item.url}
                  width={500}
                  height={500}
                />
                <h2>{item.title}</h2>
              </div>
            )
          })
        }
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://api.nasa.gov/planetary/apod?api_key=eNnvWXRXeAoi46DuYePffd8AWw13mGbJukMfZMDn&count=20')
  const info = await res.json()
  
  return {
    props: {
      info,
    }
  }
}